### PR TITLE
Maspawn skin

### PR DESCRIPTION
**Pull request by m-hynek**
#6 

Tested, looks good

image

### CODE REVIEW

**Comment by WheteThunger** [comment]
Looks good at a glance. When I have a little more time, I'll take a closer look, test and merge if all goes well.

**Comment by WheteThunger** [comment]
Have you tested if this works with redirect skins? Not sure if it will be an issue. See the `maskin` implementation and the `IsRedirectSkin` method for reference.

If there is an issue, we can probably update `DeterminePrefabFromPlayerActiveDeployable` to call `IsRedirectSkin` and update the latter method to output the full resource path so that `DeterminePrefabFromPlayerActiveDeployable` can return it.

**Comment by m-hynek** [comment]
I couldn't identify any issue with these skins.

Tested:
door.hinged.metal -> door.hinged.industrial.a
innertube -> innertube.horse
innertube -> innertube.unicorn
discofloor -> discofloor.largetiles
skylantern -> skylantern.skylantern.green
skylantern -> skylantern.skylantern.purple
skylantern -> skylantern.skylantern.orange

**Comment by WheteThunger** [comment]
I see, I think those are fine because when you are holding the item (e.g., `door.hinged.industrial.a`) it has no skin. It seems redirect skins are mainly used when a player wants to change a skin. For instance, when changing an item's skin at repair bench, if the target skin or source skin has a redirect, it'll change the item id.

**Review by WheteThunger — APPROVED** [review]

**Pull request merged**
